#### StatisticsVsML 

In [2]:
import numpy as np
X = np.arange(6).reshape(2,3)
print(X.ndim)
X.shape
# -> 이렇게 하는 사람도 있음 

2


(2, 3)

In [3]:
X1 = np.arange(6).reshape((2,3))
print(X1.ndim)
X1.shape

2


(2, 3)

In [4]:
X

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
X.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [6]:
X[0,1] == X.T[1,0]

True

In [7]:
w = np.random.randn(3)
b = 0.1
w, b

(array([ 0.16532912, -0.31491788,  0.86727804]), 0.1)

In [8]:
w + b

array([ 0.26532912, -0.21491788,  0.96727804])

In [9]:
X.dot(w) + b 

array([1.5196382 , 3.67270603])

In [10]:
b * np.array([[1,1]])

array([[0.1, 0.1]])

In [12]:
X.dot(w) + b * np.array([[1,1]])

array([[1.5196382 , 3.67270603]])